src/ProduitsBundle/Entity/Produit.php
<?php

namespace ProduitsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Produit
 *
 * @ORM\Table(name="produit")
 * @ORM\Entity
 */
class Produit
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id_produit", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idProduit;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=50, nullable=false)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="reference", type="string", length=255, nullable=false)
     */
    private $reference;

    /**
     * @var string
     *
     * @ORM\Column(name="categorie", type="string", length=50, nullable=false)
     */
    private $categorie;

    /**
     * @var integer
     *
     * @ORM\Column(name="quantite", type="integer", nullable=false)
     */
    private $quantite;

    /**
     * @var integer
     *
     * @ORM\Column(name="prix", type="integer", nullable=false)
     */
    private $prix;

    /**
     * @var string
     *
     * @ORM\Column(name="image", type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255, nullable=false)
     */
    private $description;

    /**
     * @var integer
     *
     * @ORM\Column(name="etoile", type="integer", nullable=false)
     */
    private $etoile = '3';
    /**
     * @var ProduitsBundle\Entity\Fournisseur
     * @ORM\ManyToOne(
     *     targetEntity="ProduitsBundle\Entity\Fournisseur",
     *
     * )
     * @ORM\JoinColumn(name="fournisseur_id", referencedColumnName="id")
     */
    private $fournisseur_id;

    /**
     * @var int
     *
     * @ORM\Column(name="datecreation", type="datetime", nullable=false)
     *
     */
    private $datecreation;

    /**
     * @return int
     */
    public function getDatecreation()
    {
        return $this->datecreation;
    }

    /**
     * @param int $datecreation
     */
    public function setDatecreation($datecreation)
    {
        $this->datecreation = $datecreation;
    }


    /**
     * @return mixed
     */
    public function getFournisseurId()
    {
        return $this->fournisseur_id;
    }

    /**
     * @param mixed $fournisseur_id
     */
    public function setFournisseurId($fournisseur_id)
    {
        $this->fournisseur_id = $fournisseur_id;
    }

    /**
     * @return int
     */
    public function getIdProduit()
    {
        return $this->idProduit;
    }

    /**
     * @param int $idProduit
     */
    public function setIdProduit($idProduit)
    {
        $this->idProduit = $idProduit;
    }

    /**
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param string $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return string
     */
    public function getReference()
    {
        return $this->reference;
    }

    /**
     * @param string $reference
     */
    public function setReference($reference)
    {
        $this->reference = $reference;
    }

    /**
     * @return string
     */
    public function getCategorie()
    {
        return $this->categorie;
    }

    /**
     * @param string $categorie
     */
    public function setCategorie($categorie)
    {
        $this->categorie = $categorie;
    }

    /**
     * @return int
     */
    public function getQuantite()
    {
        return $this->quantite;
    }

    /**
     * @param int $quantite
     */
    public function setQuantite($quantite)
    {
        $this->quantite = $quantite;
    }

    /**
     * @return int
     */
    public function getPrix()
    {
        return $this->prix;
    }

    /**
     * @param int $prix
     */
    public function setPrix($prix)
    {
        $this->prix = $prix;
    }

    /**
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param string $image
     */
    public function setImage($image)
    {
        $this->image = $image;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * @return int
     */
    public function getEtoile()
    {
        return $this->etoile;
    }

    /**
     * @param int $etoile
     */
    public function setEtoile($etoile)
    {
        $this->etoile = $etoile;
    }


}

src/ProduitsBundle/Controller/DefaultController.php
<?php

namespace ProduitsBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    public function indexAction()
    {
        return $this->render('ProduitsBundle:Default:index.html.twig');
    }
}

src/ProduitsBundle/Resources/views/Default/ajoutfournisseur.html.twig
{% extends 'baseBack.html.twig' %}
{% block content %}
    <form method="post" novalidate="novalidate" enctype="multipart/form-data">
        <div class="form-group">
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-label-group">
                        <input type="text" id="Nom" name="nom" class="form-control" placeholder="Nom" required="required" autofocus="autofocus">
                        <label for="Nom">Nom</label>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-label-group">
                        <input type="number" id="Numero" name="numero" class="form-control" placeholder="numero" required="required" autofocus="autofocus">
                        <label for="Numero">Numero</label>
                    </div>
                </div>

            </div>
        </div>





        <button type="submit" class="btn btn-primary btn-block" href="login.html">Ajouter le produit</button>
    </form>


{% endblock %}

src/ProduitsBundle/Resources/views/Default/ajoutproduit.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="text-center" style="margin-top: 20px">
        <h3>La liste de nos produits</h3>
    </div>
    <div class="row">
        <div class="container col-2 text-left"  style="margin-top: 20px;margin-right: 290px">

        </div>
        <div class="col-md-3 " style="margin-right: 250px;margin-top: 20px">
            <label class="text-black" for="fname">Rechercher: </label>
            <input type="text" id="recherche" >
        </div>
    </div>
    <div class="site-section" size="1">

        <div id="produits" class="container">
            <div class="row">
                {% for p in offres %}
                    <div class="col-md-6 col-lg-4 mb-4">
                        <a href="#" class="unit-1 text-center">
                            <img src="{{asset('ressources/images/offre/'~p.photo )}}"  alt="Image" class="img-fluid">
                            <div class="unit-1-text">
                                <h3 class="unit-1-heading">{{ p.nom }}</h3>
                                <p class="px-5">{{ p.description }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>

{% endblock %}
{% block javascripts %}
    <script src="{{ asset('Bundles/AppBundle/js/jquery-3.3.1.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/jquery-migrate-3.0.1.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/jquery-ui.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/popper.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/bootstrap.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/owl.carousel.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/jquery.stellar.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/jquery.countdown.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/jquery.magnific-popup.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/bootstrap-datepicker.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/aos.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/main.js')}}"></script>
{% endblock %}

src/ProduitsBundle/Resources/views/Default/consulter_produits.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="text-center" style="margin-top: 20px">
        <h3>La liste de nos produits</h3>
    </div>
    <div class="row">
    <div class="container col-2 text-left"  style="margin-top: 20px;margin-right: 290px">
        <select class="custom-select" id="categorie">
<<<<<<< HEAD
            <option value="Bricollage">Bricolage</option>
=======
            <option value="Bricollage">Bricollage</option>
>>>>>>> 1453b8fe36090e5d7587461cd7c31b60229a01ab
            <option value="Jardinage">Jardinage</option>
            <option value="Plomberie">Plomberie</option>
            <option value="Batiment"> Batiment</option>
            <option selected="selected" value="all">All</option>
        </select >
    </div>
        <div class="col-md-3 " style="margin-right: 250px;margin-top: 20px">
            <label class="text-black" for="fname">Rechercher: </label>
            <input type="text" id="recherche" >
        </div>
    </div>
    <div class="site-section" size="1">

        <div id="produits" class="container">
            <div class="row">
                {% for p in produits %}
                <div class="col-md-6 col-lg-4 mb-4">
<<<<<<< HEAD
                    <a href="{{ path('produits_detailsproduit', {'idProduit': p.idProduit }) }}" class="unit-1 text-center">
                        <img src="{{asset('ressources/images/produit/'~p.image )}}"  alt="Image" class="img-fluid" width="300" height="300">
                        <div class="unit-1-text">
                            <h4 >{{ p.nom }}</h4>
                            <p class="px-5" style="margin-bottom: 80px" >{{ p.prix }} dt</p>


=======
                    <a href="#" class="unit-1 text-center">
                        <img src="{{asset('ressources/images/produit/'~p.image )}}"  alt="Image" class="img-fluid">
                        <div class="unit-1-text">
                            <h3 class="unit-1-heading">{{ p.nom }}</h3>
                            <p class="px-5">{{ p.description }}</p>
>>>>>>> 1453b8fe36090e5d7587461cd7c31b60229a01ab
                        </div>
                    </a>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
    <script>
        $(document).ready(function(){
            $("#categorie").change(function(){
                if ($("#categorie").val() !="all") {
                    $("#produits").empty();
                    var content =  "<div class=\"row\">";
                    {% for p in produits %}
                    if ($("#categorie").val() =="{{ p.categorie }}")
                        content +="<div class=\"col-md-6 col-lg-4 mb-4\">\n" +
                            "                    <a href=\"#\" class=\"unit-1 text-center\">\n" +
<<<<<<< HEAD
                            "                        <img  width=\"300\" height=\"300\" src=\""+"{{ asset('ressources/images/produit/'~p.image ) }}"+"\"  alt=\"Image\" class=\"img-fluid\">\n" +
                            "                        <div class=\"unit-1-text\">\n" +
                            "                            <h4 >{{ p.nom }}"+"</h4>\n" +
                            "                            <p class=\"px-5\" style=\"margin-bottom: 80px\">"+"{{ p.prix }}"+"</p>\n" +
=======
                            "                        <img src=\""+"{{ asset('ressources/images/produit/'~p.image ) }}"+"\"  alt=\"Image\" class=\"img-fluid\">\n" +
                            "                        <div class=\"unit-1-text\">\n" +
                            "                            <h3 class=\"unit-1-heading\">"+"{{ p.nom }}"+"</h3>\n" +
                            "                            <p class=\"px-5\">"+"{{ p.description }}"+"</p>\n" +
>>>>>>> 1453b8fe36090e5d7587461cd7c31b60229a01ab
                            "                        </div>\n" +
                            "                    </a>\n" +
                            "                </div>"

<<<<<<< HEAD

=======
>>>>>>> 1453b8fe36090e5d7587461cd7c31b60229a01ab
                    {% endfor %}
                    content+="</div>";
                    $("#produits").append(content);
                }else {
                    $("#produits").empty();
                    var content =  "<div class=\"row\">";
                    {% for p in produits %}

                        content +="<div class=\"col-md-6 col-lg-4 mb-4\">\n" +
                            "                    <a href=\"#\" class=\"unit-1 text-center\">\n" +
<<<<<<< HEAD
                            "                        <img  width=\"300\" height=\"300\" src=\""+"{{ asset('ressources/images/produit/'~p.image ) }}"+"\"  alt=\"Image\" class=\"img-fluid\">\n" +
                            "                        <div class=\"unit-1-text\">\n" +
                            "                            <h3 class=\"unit-1-heading\">"+"{{ p.nom }}"+"</h3>\n" +
                            "                            <p class=\"px-5\" style=\"margin-bottom: 80px\">"+"{{ p.prix }}"+"</p>\n" +

=======
                            "                        <img src=\""+"{{ asset('ressources/images/produit/'~p.image ) }}"+"\"  alt=\"Image\" class=\"img-fluid\">\n" +
                            "                        <div class=\"unit-1-text\">\n" +
                            "                            <h3 class=\"unit-1-heading\">"+"{{ p.nom }}"+"</h3>\n" +
                            "                            <p class=\"px-5\">"+"{{ p.description }}"+"</p>\n" +
>>>>>>> 1453b8fe36090e5d7587461cd7c31b60229a01ab
                            "                        </div>\n" +
                            "                    </a>\n" +
                            "                </div>"

                    {% endfor %}
                    content+="</div>";
                    $("#produits").append(content);
                }




            });
            $("#recherche").keyup(function(){
                if ($("#recherche").val() !="") {
                    $("#produits").empty();
                    var content =  "<div class=\"row\">";
                    {% for p in produits %}
                    if ("{{ p.categorie }}".toLowerCase().includes($("#recherche").val().toLowerCase()) || "{{ p.description }}".toLowerCase().includes($("#recherche").val().toLowerCase()) || "{{ p.nom }}".toLowerCase().includes($("#recherche").val().toLowerCase()))
                        content +="<div class=\"col-md-6 col-lg-4 mb-4\">\n" +
                            "                    <a href=\"#\" class=\"unit-1 text-center\">\n" +
<<<<<<< HEAD
                            "                        <img  width=\"300\" height=\"300\" src=\""+"{{ asset('ressources/images/produit/'~p.image ) }}"+"\"  alt=\"Image\" class=\"img-fluid\">\n" +
                            "                        <div class=\"unit-1-text\">\n" +
                            "                            <h3 class=\"unit-1-heading\">"+"{{ p.nom }}"+"</h3>\n" +
                            "                            <p class=\"px-5\" style=\"margin-bottom: 80px\">"+"{{ p.prix }}"+"</p>\n" +
=======
                            "                        <img src=\""+"{{ asset('ressources/images/produit/'~p.image ) }}"+"\"  alt=\"Image\" class=\"img-fluid\">\n" +
                            "                        <div class=\"unit-1-text\">\n" +
                            "                            <h3 class=\"unit-1-heading\">"+"{{ p.nom }}"+"</h3>\n" +
                            "                            <p class=\"px-5\">"+"{{ p.description }}"+"</p>\n" +
>>>>>>> 1453b8fe36090e5d7587461cd7c31b60229a01ab
                            "                        </div>\n" +
                            "                    </a>\n" +
                            "                </div>"

                    {% endfor %}
                    content+="</div>";
                    $("#produits").append(content);
                }
                else {
                    $("#produits").empty();
                    var content =  "<div class=\"row\">";
                    {% for p in produits %}

                    content +="<div class=\"col-md-6 col-lg-4 mb-4\">\n" +
                        "                    <a href=\"#\" class=\"unit-1 text-center\">\n" +
<<<<<<< HEAD
                        "                        <img  width=\"300\" height=\"300\" src=\""+"{{ asset('ressources/images/produit/'~p.image ) }}"+"\"  alt=\"Image\" class=\"img-fluid\">\n" +
                        "                        <div class=\"unit-1-text\">\n" +
                        "                            <h3 class=\"unit-1-heading\">"+"{{ p.nom }}"+"</h3>\n" +
                        "                            <p class=\"px-5\" style=\"margin-bottom: 80px\">"+"{{ p.prix }}"+"</p>\n" +
=======
                        "                        <img src=\""+"{{ asset('ressources/images/produit/'~p.image ) }}"+"\"  alt=\"Image\" class=\"img-fluid\">\n" +
                        "                        <div class=\"unit-1-text\">\n" +
                        "                            <h3 class=\"unit-1-heading\">"+"{{ p.nom }}"+"</h3>\n" +
                        "                            <p class=\"px-5\">"+"{{ p.description }}"+"</p>\n" +
>>>>>>> 1453b8fe36090e5d7587461cd7c31b60229a01ab
                        "                        </div>\n" +
                        "                    </a>\n" +
                        "                </div>"

                    {% endfor %}
                    content+="</div>";
                    $("#produits").append(content);
                }

            });
        });
    </script>

{% endblock %}
{% block javascripts %}
    <script src="{{ asset('Bundles/AppBundle/js/jquery-3.3.1.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/jquery-migrate-3.0.1.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/jquery-ui.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/popper.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/bootstrap.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/owl.carousel.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/jquery.stellar.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/jquery.countdown.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/jquery.magnific-popup.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/bootstrap-datepicker.min.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/aos.js')}}"></script>
    <script src="{{ asset('Bundles/AppBundle/js/main.js')}}"></script>
{% endblock %}

src/ProduitsBundle/Resources/views/Default/detailsproduit.html.twig
{%extends 'base.html.twig'  %}
 {% block body %}



     <div class="site-section bg-light">
         <div class="container">
             <div class="row">

                 <div class="col-md-5">

                     <img src="{{asset('ressources/images/produit/'~produit.image )}}"  alt="Image" class="img-fluid" width="500" height="500">


                 </div>
                 <div class="col-md-7 mb-5">



                     <form action="#" class="p-5 bg-white">


                         <div class="row form-group">
                             <div class="col-md-6 mb-3 mb-md-0">
                                 <label class="text-black" for="fname">Nom du produit:</label>
<p >{{ produit.nom }}</p>
                             </div>
                             <div class="col-md-6">
                                 <label class="text-black" for="lname">Reference:</label>
                                 <p>{{ produit.reference}}</p>
                             </div>
                         </div>

                         <div class="row form-group">

                             <div class="col-md-12">
                                 <label class="text-black" for="email">Quantite:</label>
                                 <p>{{ produit.quantite }} en stock</p>
                             </div>
                         </div>

                         <div class="row form-group">

                             <div class="col-md-12">
                                 <label class="text-black" for="subject">Prix unitaire:</label>
                                 <p>{{ produit.prix }} dt</p>
                             </div>
                         </div>

                         <div class="row form-group">
                             <div class="col-md-12">
                                 <label class="text-black" for="message">Description</label>
                                 <p>{{ produit.description}}</p>
                             </div>
                         </div>

                         <div class="addtocart">

                                 <a  class="btn fa-add" href="{{ path("addProduitPanier",{idProduit:produit.idProduit}) }}" >
                                     <span class="glyph fa-edit icon-edit"   ></span>
                                     {% trans %} Ajouter Au Panier {% endtrans %}
                                 </a>

                         </div>


                     </form>
                 </div>
             </div>
         </div>
     </div>

 {% endblock %}

src/ProduitsBundle/Resources/views/Default/liste_fournisseurs.html.twig
{% extends 'baseBack.html.twig' %}
{% block content %}

    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table"></i>
            Data Table Example</div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nom</th>
                        <th>Numero</th>
<<<<<<< HEAD
<th></th>
                        <th></th>
=======

>>>>>>> 1453b8fe36090e5d7587461cd7c31b60229a01ab
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Nom</th>
                        <th>Numero</th>
<<<<<<< HEAD
<th></th>
                        <th></th>
=======

>>>>>>> 1453b8fe36090e5d7587461cd7c31b60229a01ab
                    </tr>
                    </tfoot>
                    <tbody>
                    {% for i in fournisseurs %}
                        <tr>
                            <td>{{  i.id }}</td>
                            <td>{{  i.nom }}</td>
                            <td>{{  i.numero }}</td>
<<<<<<< HEAD
                            <td><button class="btn-success">Modifier</button></td>
                            <td><button class="btn-danger">Supprimer</button></td>
=======

>>>>>>> 1453b8fe36090e5d7587461cd7c31b60229a01ab
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>





{% endblock %}

src/ProduitsBundle/Resources/views/Default/liste_produits.html.twig
{% extends 'baseBack.html.twig' %}
{% block content %}
    <script type="text/javascript">

        function viewImage(imgsrc) {
            document.getElementById("image").src = "{{ asset('ressources/images/produit/') }}"+imgsrc;

        }
    </script>
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table"></i>
            Data Table Example</div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nom</th>
                        <th>Reference</th>
                        <th>Categorie</th>
                        <th>Quantiite</th>
                        <th>Prix</th>
                        <th>Image</th>
                        <th>Description</th>
                        <th>Fournisseur</th>
                        <th>Etoiles</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Nom</th>
                        <th>Reference</th>
                        <th>Categorie</th>
                        <th>Quantiite</th>
                        <th>Prix</th>
                        <th>Image</th>
                        <th>Description</th>
                        <th>Fournisseur</th>
                        <th>Etoiles</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    {% for i in produits %}
                    <tr>
                        <td>{{  i.idProduit }}</td>
                        <td>{{  i.nom }}</td>
                        <td>{{  i.reference }}</td>
                        <td>{{  i.categorie }}</td>
                        <td>{{  i.quantite }}</td>
                        <td>{{  i.prix}}</td>
                        <td><button onclick="viewImage('{{ i.image }}');"   data-toggle="modal" data-target="#imageModal">View Image</button> </td>

                        <td>{{  i.description }}</td>
                        <td>{{  i.fournisseurId.nom }}</td>
                        <td>{{  i.etoile }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="modal fade" id="imageModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">

                    <div><img id="image" width="500" height="500"></div>

                </div>
            </div>
        </div>



{% endblock %}

src/ProduitsBundle/Resources/views/Default/modifierproduit.html.twig
{% extends 'baseBack.html.twig' %}
{% block content %}
    <form method="post" novalidate="novalidate" enctype="multipart/form-data">
        <div class="form-group">
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-label-group">
                        <input type="text" id="Nom" name="nom" class="form-control" placeholder="Nom" value="{{ produit.nom }}" required="required" autofocus="autofocus">
                        <label for="Nom">Nom</label>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-label-group">
                        <input type="text" id="reference" name="reference" class="form-control" value="{{ produit.reference }}" placeholder="Reference" required="required">
                        <label for="reference">Reference</label>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-label-group">
                        <input type="text" id="categorie" name="categorie" class="form-control" value="{{ produit.categorie }}" placeholder="categorie" required="required" autofocus="autofocus">
                        <label for="categorie">Categorie</label>
                    <!--<select></select>-->
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-label-group">
                        <input type="number" id="quantite" name="quantite" class="form-control" value="{{ produit.quantite }}" required="required">
                        <label for="quantite">Quantite</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-label-group">
                        <input type="number" id="prix" name="prix" class="form-control" value="{{ produit.prix }}"  required="required" autofocus="autofocus">
                        <label for="prix">Prix</label>
                        <!--<select></select>-->
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-label-group">
                        <input type="text" id="description" name="description" class="form-control" value="{{ produit.description }}" placeholder="description" required="required">
                        <label for="description">Description</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-label-group">
                        <select id="fournisseur" disabled="disabled" style="width:100%" class="form-control custom-select"  name="fournisseur" data-rule-required="true">
                            {% for f in fournisseurs %}
                                {% if f == produit.fournisseurId %}
                                <option selected="selected" value="{{ f.id }}">{{ f.nom }}</option>
                                {% else %}
                                    <option value="{{ f.id }}">{{ f.nom }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-label-group">
                        <input id="logo" type="file" name="image" data-buttontext="Choose image"  data-buttonname="btn-outline btn-primary" data-iconname="ti-image" data-rule-accept="image/*" class="filestyle">
                    </div>
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary btn-block" href="login.html">Modifier le produit</button>
    </form>


{% endblock %}

src/ProduitsBundle/Resources/views/Default/produit.html.twig
{% extends 'baseBack.html.twig' %}
{% block content %}



{% endblock %}